; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27039.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\LeHieu\AppData\Local\Temp\.NETFramework,Version=v4.6.AssemblyAttributes.cpp"
